actions:
  - from: demo_app1
    component: "demoApp" # in case repo name doesn't fit
    update:
      - repo: demo_deploy1
        file: versions.properties
        regex: '(?P<key>\s*demo_app1_version:\s*)(?P<value>v.*?)(?P<other>$|\s+\.*)'

  